/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsRoadmapRouteImport } from './routes/docs.roadmap'
import { Route as DocsConceptsAgentRouteImport } from './routes/docs.concepts.agent'
import { Route as DocsConceptsCallbackHandlerRouteImport } from './routes/docs.concepts.callback-handler'
import { Route as DocsConceptsChatModelRouteImport } from './routes/docs.concepts.chat-model'
import { Route as DocsConceptsOutputParserRouteImport } from './routes/docs.concepts.output-parser'
import { Route as DocsConceptsPromptTemplateRouteImport } from './routes/docs.concepts.prompt-template'
import { Route as DocsConceptsRagChainRouteImport } from './routes/docs.concepts.rag-chain'
import { Route as DocsConceptsRunnableRouteImport } from './routes/docs.concepts.runnable'
import { Route as DocsConceptsRunnableParallelRouteImport } from './routes/docs.concepts.runnable-parallel'
import { Route as DocsConceptsRunnableSequenceRouteImport } from './routes/docs.concepts.runnable-sequence'
import { Route as DocsConceptsToolRouteImport } from './routes/docs.concepts.tool'
import { Route as DocsConceptsVectorStoreRouteImport } from './routes/docs.concepts.vector-store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRoadmapRoute = DocsRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsAgentRoute = DocsConceptsAgentRouteImport.update({
  id: '/concepts/agent',
  path: '/concepts/agent',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsCallbackHandlerRoute =
  DocsConceptsCallbackHandlerRouteImport.update({
    id: '/concepts/callback-handler',
    path: '/concepts/callback-handler',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsConceptsChatModelRoute = DocsConceptsChatModelRouteImport.update({
  id: '/concepts/chat-model',
  path: '/concepts/chat-model',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsOutputParserRoute =
  DocsConceptsOutputParserRouteImport.update({
    id: '/concepts/output-parser',
    path: '/concepts/output-parser',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsConceptsPromptTemplateRoute =
  DocsConceptsPromptTemplateRouteImport.update({
    id: '/concepts/prompt-template',
    path: '/concepts/prompt-template',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsConceptsRagChainRoute = DocsConceptsRagChainRouteImport.update({
  id: '/concepts/rag-chain',
  path: '/concepts/rag-chain',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRunnableRoute = DocsConceptsRunnableRouteImport.update({
  id: '/concepts/runnable',
  path: '/concepts/runnable',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRunnableParallelRoute =
  DocsConceptsRunnableParallelRouteImport.update({
    id: '/concepts/runnable-parallel',
    path: '/concepts/runnable-parallel',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsConceptsRunnableSequenceRoute =
  DocsConceptsRunnableSequenceRouteImport.update({
    id: '/concepts/runnable-sequence',
    path: '/concepts/runnable-sequence',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsConceptsToolRoute = DocsConceptsToolRouteImport.update({
  id: '/concepts/tool',
  path: '/concepts/tool',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsVectorStoreRoute = DocsConceptsVectorStoreRouteImport.update({
  id: '/concepts/vector-store',
  path: '/concepts/vector-store',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/agent': typeof DocsConceptsAgentRoute
  '/docs/concepts/callback-handler': typeof DocsConceptsCallbackHandlerRoute
  '/docs/concepts/chat-model': typeof DocsConceptsChatModelRoute
  '/docs/concepts/output-parser': typeof DocsConceptsOutputParserRoute
  '/docs/concepts/prompt-template': typeof DocsConceptsPromptTemplateRoute
  '/docs/concepts/rag-chain': typeof DocsConceptsRagChainRoute
  '/docs/concepts/runnable': typeof DocsConceptsRunnableRoute
  '/docs/concepts/runnable-parallel': typeof DocsConceptsRunnableParallelRoute
  '/docs/concepts/runnable-sequence': typeof DocsConceptsRunnableSequenceRoute
  '/docs/concepts/tool': typeof DocsConceptsToolRoute
  '/docs/concepts/vector-store': typeof DocsConceptsVectorStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs': typeof DocsIndexRoute
  '/docs/concepts/agent': typeof DocsConceptsAgentRoute
  '/docs/concepts/callback-handler': typeof DocsConceptsCallbackHandlerRoute
  '/docs/concepts/chat-model': typeof DocsConceptsChatModelRoute
  '/docs/concepts/output-parser': typeof DocsConceptsOutputParserRoute
  '/docs/concepts/prompt-template': typeof DocsConceptsPromptTemplateRoute
  '/docs/concepts/rag-chain': typeof DocsConceptsRagChainRoute
  '/docs/concepts/runnable': typeof DocsConceptsRunnableRoute
  '/docs/concepts/runnable-parallel': typeof DocsConceptsRunnableParallelRoute
  '/docs/concepts/runnable-sequence': typeof DocsConceptsRunnableSequenceRoute
  '/docs/concepts/tool': typeof DocsConceptsToolRoute
  '/docs/concepts/vector-store': typeof DocsConceptsVectorStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/agent': typeof DocsConceptsAgentRoute
  '/docs/concepts/callback-handler': typeof DocsConceptsCallbackHandlerRoute
  '/docs/concepts/chat-model': typeof DocsConceptsChatModelRoute
  '/docs/concepts/output-parser': typeof DocsConceptsOutputParserRoute
  '/docs/concepts/prompt-template': typeof DocsConceptsPromptTemplateRoute
  '/docs/concepts/rag-chain': typeof DocsConceptsRagChainRoute
  '/docs/concepts/runnable': typeof DocsConceptsRunnableRoute
  '/docs/concepts/runnable-parallel': typeof DocsConceptsRunnableParallelRoute
  '/docs/concepts/runnable-sequence': typeof DocsConceptsRunnableSequenceRoute
  '/docs/concepts/tool': typeof DocsConceptsToolRoute
  '/docs/concepts/vector-store': typeof DocsConceptsVectorStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/features'
    | '/docs/architecture'
    | '/docs/examples'
    | '/docs/installation'
    | '/docs/quickstart'
    | '/docs/roadmap'
    | '/docs/'
    | '/docs/concepts/agent'
    | '/docs/concepts/callback-handler'
    | '/docs/concepts/chat-model'
    | '/docs/concepts/output-parser'
    | '/docs/concepts/prompt-template'
    | '/docs/concepts/rag-chain'
    | '/docs/concepts/runnable'
    | '/docs/concepts/runnable-parallel'
    | '/docs/concepts/runnable-sequence'
    | '/docs/concepts/tool'
    | '/docs/concepts/vector-store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/docs/architecture'
    | '/docs/examples'
    | '/docs/installation'
    | '/docs/quickstart'
    | '/docs/roadmap'
    | '/docs'
    | '/docs/concepts/agent'
    | '/docs/concepts/callback-handler'
    | '/docs/concepts/chat-model'
    | '/docs/concepts/output-parser'
    | '/docs/concepts/prompt-template'
    | '/docs/concepts/rag-chain'
    | '/docs/concepts/runnable'
    | '/docs/concepts/runnable-parallel'
    | '/docs/concepts/runnable-sequence'
    | '/docs/concepts/tool'
    | '/docs/concepts/vector-store'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/features'
    | '/docs/architecture'
    | '/docs/examples'
    | '/docs/installation'
    | '/docs/quickstart'
    | '/docs/roadmap'
    | '/docs/'
    | '/docs/concepts/agent'
    | '/docs/concepts/callback-handler'
    | '/docs/concepts/chat-model'
    | '/docs/concepts/output-parser'
    | '/docs/concepts/prompt-template'
    | '/docs/concepts/rag-chain'
    | '/docs/concepts/runnable'
    | '/docs/concepts/runnable-parallel'
    | '/docs/concepts/runnable-sequence'
    | '/docs/concepts/tool'
    | '/docs/concepts/vector-store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/roadmap': {
      id: '/docs/roadmap'
      path: '/roadmap'
      fullPath: '/docs/roadmap'
      preLoaderRoute: typeof DocsRoadmapRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/agent': {
      id: '/docs/concepts/agent'
      path: '/concepts/agent'
      fullPath: '/docs/concepts/agent'
      preLoaderRoute: typeof DocsConceptsAgentRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/callback-handler': {
      id: '/docs/concepts/callback-handler'
      path: '/concepts/callback-handler'
      fullPath: '/docs/concepts/callback-handler'
      preLoaderRoute: typeof DocsConceptsCallbackHandlerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/chat-model': {
      id: '/docs/concepts/chat-model'
      path: '/concepts/chat-model'
      fullPath: '/docs/concepts/chat-model'
      preLoaderRoute: typeof DocsConceptsChatModelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/output-parser': {
      id: '/docs/concepts/output-parser'
      path: '/concepts/output-parser'
      fullPath: '/docs/concepts/output-parser'
      preLoaderRoute: typeof DocsConceptsOutputParserRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/prompt-template': {
      id: '/docs/concepts/prompt-template'
      path: '/concepts/prompt-template'
      fullPath: '/docs/concepts/prompt-template'
      preLoaderRoute: typeof DocsConceptsPromptTemplateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/rag-chain': {
      id: '/docs/concepts/rag-chain'
      path: '/concepts/rag-chain'
      fullPath: '/docs/concepts/rag-chain'
      preLoaderRoute: typeof DocsConceptsRagChainRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/runnable': {
      id: '/docs/concepts/runnable'
      path: '/concepts/runnable'
      fullPath: '/docs/concepts/runnable'
      preLoaderRoute: typeof DocsConceptsRunnableRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/runnable-parallel': {
      id: '/docs/concepts/runnable-parallel'
      path: '/concepts/runnable-parallel'
      fullPath: '/docs/concepts/runnable-parallel'
      preLoaderRoute: typeof DocsConceptsRunnableParallelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/runnable-sequence': {
      id: '/docs/concepts/runnable-sequence'
      path: '/concepts/runnable-sequence'
      fullPath: '/docs/concepts/runnable-sequence'
      preLoaderRoute: typeof DocsConceptsRunnableSequenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/tool': {
      id: '/docs/concepts/tool'
      path: '/concepts/tool'
      fullPath: '/docs/concepts/tool'
      preLoaderRoute: typeof DocsConceptsToolRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/vector-store': {
      id: '/docs/concepts/vector-store'
      path: '/concepts/vector-store'
      fullPath: '/docs/concepts/vector-store'
      preLoaderRoute: typeof DocsConceptsVectorStoreRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsRoadmapRoute: typeof DocsRoadmapRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsConceptsAgentRoute: typeof DocsConceptsAgentRoute
  DocsConceptsCallbackHandlerRoute: typeof DocsConceptsCallbackHandlerRoute
  DocsConceptsChatModelRoute: typeof DocsConceptsChatModelRoute
  DocsConceptsOutputParserRoute: typeof DocsConceptsOutputParserRoute
  DocsConceptsPromptTemplateRoute: typeof DocsConceptsPromptTemplateRoute
  DocsConceptsRagChainRoute: typeof DocsConceptsRagChainRoute
  DocsConceptsRunnableRoute: typeof DocsConceptsRunnableRoute
  DocsConceptsRunnableParallelRoute: typeof DocsConceptsRunnableParallelRoute
  DocsConceptsRunnableSequenceRoute: typeof DocsConceptsRunnableSequenceRoute
  DocsConceptsToolRoute: typeof DocsConceptsToolRoute
  DocsConceptsVectorStoreRoute: typeof DocsConceptsVectorStoreRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsRoadmapRoute: DocsRoadmapRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsConceptsAgentRoute: DocsConceptsAgentRoute,
  DocsConceptsCallbackHandlerRoute: DocsConceptsCallbackHandlerRoute,
  DocsConceptsChatModelRoute: DocsConceptsChatModelRoute,
  DocsConceptsOutputParserRoute: DocsConceptsOutputParserRoute,
  DocsConceptsPromptTemplateRoute: DocsConceptsPromptTemplateRoute,
  DocsConceptsRagChainRoute: DocsConceptsRagChainRoute,
  DocsConceptsRunnableRoute: DocsConceptsRunnableRoute,
  DocsConceptsRunnableParallelRoute: DocsConceptsRunnableParallelRoute,
  DocsConceptsRunnableSequenceRoute: DocsConceptsRunnableSequenceRoute,
  DocsConceptsToolRoute: DocsConceptsToolRoute,
  DocsConceptsVectorStoreRoute: DocsConceptsVectorStoreRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
